services:
  db:
    image: mysql:latest
    container_name: mysql-query-container
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: personal-budget
      MYSQL_USER: pf-personal-budget-query
      MYSQL_PASSWORD: pf-personal-budget-query
    volumes:
        - ./mysql-data:/var/lib/mysql